# Generated by Django 5.1.3 on 2025-02-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espacios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='espacio/', verbose_name='Imagen del espacio'),
        ),
    ]
