# Generated by Django 5.1.3 on 2025-02-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espacios', '0002_alter_espacio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='notificar',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2, verbose_name='Notificar'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='respaldo',
            field=models.FileField(blank=True, null=True, upload_to='respaldo/'),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='espacio/'),
        ),
    ]
