# Generated by Django 5.1.3 on 2025-02-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Espacios', '0003_evaluacion_email_evaluacion_notificar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='respaldo',
        ),
    ]
